# Generated by Django 5.1 on 2024-10-10 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_business_price_per_share'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='current_investment',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='business',
            name='goal',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='business',
            name='max_investment',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='business',
            name='min_investment',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='business',
            name='price_per_share',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
