# Generated by Django 5.1 on 2024-10-13 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_business_current_investment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investment',
            name='shares',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
