# Generated by Django 5.1 on 2024-10-14 11:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_investment_shares'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='description',
        ),
        migrations.RemoveField(
            model_name='business',
            name='shares_detail',
        ),
        migrations.AddField(
            model_name='business',
            name='brief_description',
            field=models.TextField(default=datetime.datetime(2024, 10, 14, 11, 22, 48, 705176, tzinfo=datetime.timezone.utc), max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='business',
            name='cover_image',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='business',
            name='describe_images',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='business',
            name='fundraise_purpose',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='business',
            name='pitch',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='business',
            name='current_investment',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='business',
            name='end_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='business',
            name='publish_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 14, 18, 22, 34, 791982), null=True),
        ),
    ]
