# Generated by Django 5.1 on 2024-10-14 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_business_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='cover_image',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='business',
            name='describe_images',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='business',
            name='end_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='business',
            name='publish_date',
            field=models.DateTimeField(),
        ),
    ]
