# Generated by Django 5.1 on 2024-10-15 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_business_cover_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='cover_image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='business',
            name='describe_images',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='business',
            name='pitch',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
