# Generated by Django 5.1 on 2024-10-15 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_business_cover_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='business_category',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='business',
            name='fundraise_purpose',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='business',
            name='pitch',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='business',
            name='status',
            field=models.CharField(default='pending', max_length=50),
        ),
    ]
