# Generated by Django 5.1 on 2024-10-15 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_business_business_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='country_located',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='province_located',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
