# Generated by Django 4.2.4 on 2024-10-20 05:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_investor_profile_picture_alter_business_cover_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='describe_images',
        ),
        migrations.CreateModel(
            name='BusinessImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='business/describe_images')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='describe_images', to='api.business')),
            ],
        ),
    ]
