# Generated by Django 5.1.2 on 2024-11-19 17:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_remove_business_describe_images_businessimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='investment',
            name='investment_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
