# Generated by Django 4.2.4 on 2024-11-19 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_rename_province_located_business_city_located_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordReset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('secret_token', models.CharField(max_length=100)),
                ('used', models.BooleanField(default=False)),
                ('expire_date', models.DateTimeField()),
            ],
        ),
        migrations.RenameField(
            model_name='business',
            old_name='city_located',
            new_name='province_located',
        ),
    ]
