# Generated by Django 4.2.4 on 2024-11-21 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_investment_investment_date'),
        ('api', '0015_passwordreset_and_more'),
    ]

    operations = [
    ]
