# Generated by Django 4.2.4 on 2024-11-21 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_merge_20241121_2121'),
    ]

    operations = [
        migrations.RenameField(
            model_name='passwordreset',
            old_name='secret_token',
            new_name='token',
        ),
    ]
