# Generated by Django 4.2.4 on 2024-11-21 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_rename_secret_token_passwordreset_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordreset',
            name='expire_date',
            field=models.DateTimeField(null=True),
        ),
    ]
