# Generated by Django 4.2.4 on 2024-11-25 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_passwordreset_expire_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='business',
            old_name='country_located',
            new_name='city_located',
        ),
        migrations.RenameField(
            model_name='business',
            old_name='fundraise_purpose',
            new_name='fundraising_purpose',
        ),
        migrations.RemoveField(
            model_name='business',
            name='price_per_share',
        ),
        migrations.RemoveField(
            model_name='investment',
            name='status',
        ),
        migrations.AddField(
            model_name='business',
            name='stock_amount',
            field=models.DecimalField(decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='business',
            name='goal',
            field=models.DecimalField(decimal_places=2, max_digits=14),
        ),
        migrations.AlterField(
            model_name='business',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('available', 'Available'), ('complete', 'Complete')], default='pending', max_length=50),
        ),
    ]
