# Generated by Django 4.2.4 on 2024-11-27 19:28

import api.models.business
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_businessdocument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessdocument',
            name='document',
            field=models.FileField(upload_to=api.models.business.BusinessDocument.upload_to),
        ),
        migrations.AlterField(
            model_name='businessimage',
            name='image',
            field=models.ImageField(upload_to=api.models.business.BusinessImage.upload_to),
        ),
    ]
